#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'yolov8-inference','console_scripts','yolo_node'
__requires__ = 'yolov8-inference'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('yolov8-inference', 'console_scripts', 'yolo_node')()
    )
